<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Version>1.15.0.7</Version>
        <Configurations>Debug;Release;DebugSteamDeck;CustomCS;Test</Configurations>
        <NoWarn>CS0649,CS0414,CS8618</NoWarn>
        <AppendPlatformToOutputPath>false</AppendPlatformToOutputPath>
    </PropertyGroup>
    <PropertyGroup Label="Test" Condition="'$(Configuration)'=='Test'">
        <DefineConstants>DEBUG;TEST</DefineConstants>
        <OutDir>$(ProjectDir)bin/Debug</OutDir>
    </PropertyGroup>
	<ItemGroup>
        <Reference Include="JetBrains.Annotations">
            <Private>false</Private>
            <HintPath>$(DalamudLibPath)\JetBrains.Annotations.dll</HintPath>
        </Reference>
        <None Update="images\icon.png" CopyToOutputDirectory="Always"/>
        <None Update="TweakPreviews\**" CopyToOutputDirectory="Always"/>
        <None Update="Decorations\**" CopyToOutputDirectory="Always"/>
        <None Remove="lib\**" />
        <Compile Remove="lib\**" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="KamiToolKit" Version="1.1.23" />
	</ItemGroup>
</Project>
