name: Build SimpleTweaksPlugin for PullRequest
on:
  pull_request:
jobs:
  build:
    runs-on: [windows-2022]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore NuGet Packages
        run: nuget restore SimpleTweaksPlugin.sln

      - name: Download Dalamud
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"
      - name: Build
        run: msbuild SimpleTweaksPlugin.sln /p:Configuration=Release

      - name: Extract Publish
        run: |
          Expand-Archive -Force ./bin/x64/Release/SimpleTweaksPlugin/latest.zip ./Artifact
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: pr-artifact
          path: ./Artifact/*
